name: Bygg og release artifakt med Maven
on:
  push:
  workflow_dispatch:
jobs:
  build:
    uses: statens-pensjonskasse/public-actions-library/.github/workflows/build-library-maven.yaml@8dc0aabd6d0cc4de62bb8fdfd4dbd9c6a923fd67 # v0.3.8
    permissions:
      contents: write
      packages: write
    secrets: inherit
    with:
      java-version: '25'
      require-release-flag: true # Lag release hvis commit har [release] i commit-meldingen