name: Build and Publish Library with Maven
on:
  push:
  workflow_dispatch:

jobs:
  build:
    uses: statens-pensjonskasse/github-actions-library/.github/workflows/build-library-maven.yaml5ab98667270683a8f3fd6ae8036497ba9e02a39e # v1.4.4
    permissions:
      contents: write
      packages: write
    secrets: inherit
    with:
      java-version: 21

  notify:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ always() && github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v4 #v4.2.2
      - name: report to slack
        uses: statens-pensjonskasse/gal-components/send-slack-notification@09f4ad5640b8e4bac7db7d66d7738f5dd0c231d6 # v0.1.2
        with:
          channel: '#panda-ci'
          status: ${{ needs.build.result }}
          message: ${{ env.commit_msg }}
          token: ${{ secrets.SLACK_BOT_TOKEN }}
